import React, { useState, useEffect } from 'react';
import { getTriggers, getCustomers, submitFeedback } from '../services/api';
import { Bell, Check, X, Shield, TrendingUp, CreditCard, Home } from 'lucide-react';

const EngagementPage = () => {
  const [customers, setCustomers] = useState([]);
  const [selectedCustomerId, setSelectedCustomerId] = useState('');
  const [triggers, setTriggers] = useState([]);
  const [loading, setLoading] = useState(true);

  useEffect(() => {
    getCustomers().then(res => {
      setCustomers(res.data);
    });
  }, []);

  useEffect(() => {
    fetchTriggers();
  }, [selectedCustomerId]);

  const fetchTriggers = () => {
    setLoading(true);
    getTriggers(selectedCustomerId).then(res => {
      // Only show pending nudges on the feed
      setTriggers(res.data.filter(t => t.status === 'pending'));
      setLoading(false);
    });
  };

  const handleAction = async (triggerId, action) => {
    // Optimistic UI update
    setTriggers(prev => prev.filter(t => t.id !== triggerId));
    
    // API call
    try {
      const trigger = triggers.find(t => t.id === triggerId);
      await submitFeedback(triggerId, trigger.customer_id, action);
    } catch (e) {
      console.error(e);
      fetchTriggers(); // Revert on failure
    }
  };

  const getIcon = (category) => {
    switch (category) {
      case 'Insurance': return <Shield size={24} className="text-blue-400" />;
      case 'Investment': return <TrendingUp size={24} className="text-emerald-400" />;
      case 'Loan': return <Home size={24} className="text-orange-400" />;
      case 'Card': return <CreditCard size={24} className="text-purple-400" />;
      default: return <Bell size={24} className="text-gray-400" />;
    }
  };

  return (
    <div className="max-w-3xl mx-auto space-y-6">
      <div className="flex justify-between items-center mb-8">
        <div>
          <h1 className="text-2xl font-bold text-white">Proactive Engagement Feed</h1>
          <p className="text-gray-400 text-sm">Customer-facing nudges generated by the RAG reasoning engine</p>
        </div>
        
        <select 
          className="bg-[#151e32] border border-white/10 rounded-xl px-4 py-2 text-white outline-none focus:border-blue-500"
          value={selectedCustomerId}
          onChange={(e) => setSelectedCustomerId(e.target.value)}
        >
          <option value="">All Customers</option>
          {customers.map(c => (
            <option key={c.id} value={c.id}>{c.name}</option>
          ))}
        </select>
      </div>

      {loading ? (
        <div className="text-white text-center py-12 animate-pulse">Loading nudges...</div>
      ) : triggers.length === 0 ? (
        <div className="glass-card p-12 flex flex-col items-center justify-center text-center">
          <div className="w-16 h-16 bg-white/5 rounded-full flex items-center justify-center mb-4">
            <Bell size={24} className="text-gray-500" />
          </div>
          <h3 className="text-lg font-medium text-white mb-2">No active nudges</h3>
          <p className="text-gray-400 text-sm">Scan a customer's profile on the dashboard to generate nudges.</p>
        </div>
      ) : (
        <div className="space-y-4">
          {triggers.map(trigger => (
            <div key={trigger.id} className="glass-card overflow-hidden group">
              <div className="p-6 border-b border-white/5">
                <div className="flex gap-4">
                  <div className="w-12 h-12 rounded-xl bg-white/5 border border-white/10 flex items-center justify-center shrink-0">
                    {getIcon(trigger.product_category)}
                  </div>
                  <div className="flex-1">
                    <div className="flex justify-between items-start">
                      <h3 className="text-lg font-semibold text-white mb-1">
                        {trigger.product_recommended}
                      </h3>
                      <span className="text-[10px] uppercase tracking-wider px-2 py-1 bg-white/10 rounded text-gray-300">
                        Confidence: {Math.round(trigger.confidence * 100)}%
                      </span>
                    </div>
                    <p className="text-gray-400 text-sm leading-relaxed mt-2">
                      <span className="font-medium text-blue-400 mr-2">Why you're seeing this:</span>
                      {trigger.explanation}
                    </p>
                  </div>
                </div>
              </div>
              
              <div className="bg-[#151e32]/50 p-4 flex justify-end gap-3">
                <button 
                  onClick={() => handleAction(trigger.id, 'dismissed')}
                  className="px-4 py-2 rounded-lg text-sm font-medium text-gray-400 hover:text-white hover:bg-white/10 transition-colors flex items-center gap-2"
                >
                  <X size={16} /> Dismiss
                </button>
                <button 
                  onClick={() => handleAction(trigger.id, 'accepted')}
                  className="sbi-gradient text-white px-6 py-2 rounded-lg text-sm font-medium hover:shadow-lg hover:shadow-blue-500/20 transition-all flex items-center gap-2"
                >
                  <Check size={16} /> Explore Offer
                </button>
              </div>
            </div>
          ))}
        </div>
      )}
    </div>
  );
};

export default EngagementPage;
